#!/bin/bash

LOGS_FoLDER="/var/log/roboshop"
sudo mkdir -p $LOGS_FoLDER
sudo chown -R ec2-user:ec2-user $LOGS_FoLDER
sudo chmod -R 755 $LOGS_FoLDER
LOGS_FILES="$LOGS_FOLDER/$0.log"

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
TIMESTAMP=$(date "+%Y-%m-%d %H:%M:%S")


if [ $USERID -ne 0 ]; then
    echo -e "$TIMESTAMP [ERROR] $R Please run this script with root access $N" | tee -a $LOGS_FILE
    exit 1 
fi

VALIDATE(){
    if [ $1 -ne 0 ]; then
        echo -e "$TIMAESTAMP [ERROR] $2 ... $R FAILURE $N" | tee -a $LOGS_FILE
        exit 1
    else
        echo -e "$TIMAESTAMP [INFO] $2 ... $R SUCCESS $N" | tee -a $LOGS_FILE
    fi
        
}

cp mango.repo /etc/yum.repos.d/mongo.repo
VALIDATE $? "ADDING Mongo repo"

dnf install mangodb-org -y &>> $LOGS_FILE
VALIDATE $? "Installing MongoDB"
